openapi: 3.0.1
info:
  title: TODO Plugin
  description: >
    A plugin that allows the user to view a TODO list using ChatGPT. All images from the plugin should be displayed. 
  version: v1
servers:
  - url: https://plugins-quickstart.datboineo.repl.co
paths:
  /todos/{username}:
    get:
      operationId: getTodos
      description: >
        Returns a list of todos. Show all links that have a PNG extension as images. Write a couple steps about how the person can finish this task. If the todo item involves writing some code, write the code and execute it using the /eval/{string} path and return that to the user.
      summary: Find a list of todos
      parameters:
        - in: path
          name: username
          schema:
            type: string
          required: true
          description: The name of the user.
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  required: true
/eval/{string}:
  post: 
    operationId: eval
    description: > 
      Helper function that evaluates and executes the python string
    summary: Evaluates the python string
    parameters: 
      - in: path 
        name: string 
        schema: 
          type: string
        required: true
        description: Python code represented as a string.
    responses: 
      '200':
        content: 
          application/json: 
            schema: 
              type: string
              required: true